# Generated by Django 3.1.4 on 2022-10-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platerak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=200)),
                ('deskripzioa', models.TextField()),
                ('prezioa', models.FloatField()),
                ('FechaCreacion', models.DateField()),
            ],
        ),
    ]
